### ISSUE TITLE
Error running `phold run` in Colab Notebook

### ISSUE THREAD

**Issue by Noonanav** [gbouras13/phold#55]
### Description

I was trying to run the Colab Notebook as published and encountered an error with limited explanation:

```
Running phold
Error occurred: Command 'phold run -i ./test_pharokka/test_pharokka.gbk -t 4 -o output_phold -p phold -f' returned non-zero exit status 1.
CPU times: user 22.1 ms, sys: 6.59 ms, total: 28.7 ms
Wall time: 4.87 s
```

Despite being connected to a T4 GPU, it appears phold is trying to run on a CPU (this could be the issue).

### What I Did

Previous chunks ran as expected and generated output:

Database Downloads:

```
Downloading phynteny models. This will take a few minutes. Please be patient :)
Downloading pharokka database. This will take a few minutes. Please be patient :)
Downloading phold database. This will take a few minutes. Please be patient :)
CPU times: user 319 ms, sys: 46.1 ms, total: 365 ms
Wall time: 1min 36s
256
```

Run pharokka:

```
Input file ON602723.1.fna exists
Running pharokka
pharokka completed successfully.
Your output is in test_pharokka.
Zipping the output directory so you can download it all in one go.
Output directory has been zipped to test_pharokka.zip
CPU times: user 260 ms, sys: 22.1 ms, total: 282 ms
Wall time: 59.2 s
```

All expected output files were generated.

Run phold:

```
Running phold
Error occurred: Command 'phold run -i ./test_pharokka/test_pharokka.gbk -t 4 -o output_phold -p phold -f' returned non-zero exit status 1.
CPU times: user 22.1 ms, sys: 6.59 ms, total: 28.7 ms
Wall time: 4.87 s
```

**Comment by gbouras13** [comment]
Hi @Noonanav ,

I reckon the issue isn't cpu - phold will run (just slower) if cpu only is available.

Would you mind downloading the `.log` file in the `output_phold` directory? If it exists?

George

**Comment by gbouras13** [comment]
Hi @Noonanav ,

The issue was phynteny - it was breaking the notebook as it requires v1 of numpy (not 2).

I've changed the notebook - please try it again :)

George

**Comment by Noonanav** [comment]
Hi @gbouras13,

It is working now! Thanks for the help,

Avery
