### ISSUE TITLE
[BUG] Limit CPU usage for 3Di prediction

### ISSUE THREAD

**Issue by valentynbez** [gbouras13/phold#60]
* phold version: 0.2.0
* Python version: 3.11.9 
* Operating System: CentOS

### Description

During CPU prediction of 3Di tokens `phold` uses all available CPUs, even though the `threads` parameter is passed. 

Command to reproduce: 
```
phold run -i largest_virus/pharokka.gbk \
    -d work/phold --threads 32 --cpu \
    -o phold --ultra_sensitive --force
```

**Comment by jamesck2** [comment]
I had this same issue

**Comment by gbouras13** [comment]
Thanks @valentynbez @jamesck2 ,

This bug is fixed now thanks for spotting it - the fix is available in the main branch (I'll make a release soon). 

Let me know if it doesn't work, my tests suggest it works.

George
