### ISSUE TITLE
Core dependencies versions

### ISSUE THREAD

**Issue by deminatanja** [gbouras13/phold#78]
Hi @gbouras13,
For citing purposes, what are the versions of core dependencies used in the current Phold (0.2.0)? I mean Foldseek, ProstT5, Colabfold.
Best regards,
Tatiana 
UPD: found in the log :) I'll close the issue and you can also delete it ;)

**Comment by gbouras13** [comment]
Hi @deminatanja ,

Sweet - just stating here on top that ProstT5 isn't really versioned, and that Colabfold v1.5 (specifically v1.5.3 and v1.5.5) were used to construct the database.

George
